#
###################################
# Site wide configuration
####################################
#
title: Daniel Li
email: danielli9988@gmail.com
description: description later
url: # the base hostname & protocol for your site
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: daniel li
  avatar: daniel.jpg
  job: "Software Developer"
  bio: "Hi! I'm currently a student at UCLA. Welcome to my blog. Maybe read some posts while you're here :)"
  email: #email address
  disqus-shortname:
  twitter: #username
  facebook: lidanieltiger
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: lidanieltiger
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: lidanieltiger
  skype: #username
  xing: #username
  instagram: lidanieltiger
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
